stages:
  - check
  - build
  - test
  - docs

# rust images are out of data.
# here the latest rust toolchain is installed manually.
.rust:
  before_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - export PATH=$HOME/.cargo/bin:$PATH
    - rustup --version
    - rustc --version
    - cargo --version

# adds sonar-scanner to path to be used in the check:sonar job.
.sonar:
  before_script:
    - export SONAR_SCANNER_VERSION=7.2.0.5079
    - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux-x64
    - curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux-x64.zip
    - unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
    - export PATH=$SONAR_SCANNER_HOME/bin:$PATH

# sonar job, runs the sonar-scanner.
check:sonar:
  extends: .sonar
  stage: check
  script:
    - sonar-scanner

# linting with clippy.
check:clippy:
  extends: .rust
  stage: check
  script:
    - rustup component add clippy
    - "cargo clippy
      --color always
      --verbose
      --all-targets
      --all-features"

# formatting check with rustfmt.
check:fmt:
  extends: .rust
  stage: check
  script:
    - rustup component add rustfmt
    - "cargo fmt
      --check
      --verbose"

# test build, verbosely, with cargo.
build:build:
  extends: .rust
  stage: build
  script:
    - "cargo build
      --color always
      --verbose"

# test run, verbosely, with cargo.
test:test:
  extends: .rust
  stage: test
  script:
    - "cargo test
      --color always
      --verbose
      --all-features
      --all-targets"

# generate rustdoc, goes to target/doc.
# stored as artifact for later.
docs:docs:
  extends: .rust
  stage: docs
  script:
    - "cargo doc"
  artifacts:
    paths:
      - target/doc
