[workspace]
members = [
    "bench",
    "e2e",
    "example/arithmetic-expression",
    "example/demo",
    "example/left-recursion",
    "example/macros",
    "example/meta",
    "ppeg-cli",
    "ppeg-core",
    "ppeg-wasm",
]
resolver = "1"

[workspace.dependencies]

[profile.profiling]
inherits = "release"
debug = true
