# Project identification
sonar.projectKey=productive-peg_ppeg
sonar.organization=productive-peg


# Language and source settings
source.language=rust
sonar.sources=.


# Test settings
sonar.test.inclusions=**/*_test.rs
sonar.coverage.exclusions=**/*_test.rs
