//! PPEG meta defines the meta grammar that can be used to write grammars.
//! The meta grammar is translated into a grammar that the parser uses to parse an input.
//!
//! Character
//! - A single character that must be matched for the rule to progress the input.
//! - For example the rule `char_c := { 'c' }` matches the character 'c'.
//!
//! Sequence
//! - A series of rule that must be in order for the rule to match.
//! - For example the rule `sequence := { char_c, char_c }` matches character 'c' followed by character 'c'.
//!
//! Choice
//! - A series of rules that any one of them can match for the rule to match.
//! - For example the rule `choice := { char_c | 'b' }` matches either character 'c' or character 'b'.
//!
//! Zero or more
//! - A rule that can match zero or more times.
//! - For example the rule `zero_or_more := { char_c* }` matches zero or more characters 'c'.
//!
//! One or more
//! - A rule that must match one or more times.
//! - For example the rule `one_or_more := { char_c+ }` matches one or more characters 'c'.
//!
//! Named rule
//! - A rule that matches the result of another rule.
//! - For example the rule `named_rule := { char_c }` matches the result of the rule `char_c`.
//! - This is more powerful when used in other rules, for example `sequence := { char_c, named_rule }`.
//! - Which matches with `char_c` twice.
//!
//! An example using this meta grammar to define some rules of a grammar.
//! ```txt
//! // A character rule that matches the character 'c'.
//! char_c := { 'c' }
//!
//! // The sequence of characters that must be matched in order for the rule to match.
//! // In this case must match with character 'c' followed by character 'c'.
//! sequence := { char_c, char_c }
//!
//! // The pipe symbol indicates that the given rule can match either the left or right side of the pipe.
//! // Trying to match with the left side first, then right side if the left side fails.
//! choice := { char_c | sequence }
//!
//! // The asterisk indicates that the given rule can match zero or more times.
//! zero_or_more := { char_c* }
//!
//! // The plus sign indicates that the given rule must match one or more times.
//! one_or_more := { char_c+ }
//!
//! // Takes the name of the rule to match
//! named_rule := { char_c }
//!
//! // A more complex rule that is matches with 'a' or a sequence of 'b' followed by 'c'.
//! complex := { 'a' | { 'b', char_c } }
//! ```

use crate::{
  error::MetaError,
  parser::{Expression, Grammar, Rule},
};

#[derive(Debug, Clone, PartialEq, Copy)]
pub struct Meta {}

impl<'a> Meta {
  pub fn new() -> Self {
    Self {}
  }

  // Generate a grammar from the given input string.
  // The input string should be in the format of the meta grammar,
  // which is defined in the documentation of this module.
  pub fn generate(self, input: &'a str) -> Result<Grammar<'a>, MetaError> {
    self.parse_grammar(self.preprocess(input))
  }

  // Preprocess takes the input string and removes any comments and unnecessary whitespace.
  // It also splits the input into each rule so that each rule can be individually parsed.
  // Returns a vector of strings, where each string is a rule that can be parsed into a Rule.
  fn preprocess(self, input: &'a str) -> Vec<&'a str> {
    input
      .lines()
      .map(|line| line.trim())
      .filter(|line| !line.is_empty() && !line.starts_with("//"))
      .collect()
  }

  // Parses a grammar from the vector of rules generated by the preprocess function.
  fn parse_grammar(self, rules: Vec<&'a str>) -> Result<Grammar<'a>, MetaError> {
    let mut grammar = Grammar::default();

    for rule in rules {
      match self.parse_rule(rule) {
        Ok(parsed_rule) => grammar.insert(parsed_rule),
        Err(e) => {
          return Err(e);
        }
      }
    }

    Ok(grammar)
  }

  // Parse rule generates a rule from the given input string.
  // A rule is defined as a name followed by ':=' and then an expression.
  // For example the rule `char_c := { 'c' }` is parsed into a rule with
  // name `char_c` and expression `{ 'c' }`.
  // The input should contain only a single rule, and it can span multiple lines.
  fn parse_rule(self, input: &'a str) -> Result<Rule<'a>, MetaError> {
    let split = input.split(":=").collect::<Vec<&str>>();

    if split.len() != 2 {
      return Err(MetaError::InvalidRule {
        position: 0,
        rule: input.to_string(),
      });
    }

    let (name, expr) = (split[0].trim(), split[1].trim());

    Ok(Rule {
      name,
      expression: self.parse_expression(expr)?,
    })
  }

  // Parses the expression part of a rule.
  // An expression can be a character, sequence, choice,
  // zero or more, one or more, or a named rule.
  // Each expression can be uniquely identified by a character in the expression.
  // They are always surrounded by curly braces, for example `{ 'c' }` or `{ char_c, char_c }`.
  fn parse_expression(self, input: &'a str) -> Result<Expression<'a>, MetaError> {
    let input = input.trim();

    if !input.starts_with("{") || !input.ends_with("}") {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let inner = &input[1..input.len() - 1].trim();

    if inner.starts_with('\'') && inner.ends_with('\'') {
      return Self::parse_character(inner);
    }

    if inner.contains(',') {
      return self.parse_sequence(inner);
    }

    if inner.contains('|') {
      return self.parse_choice(inner);
    }

    if inner.ends_with('*') {
      return self.parse_zero_or_more(inner);
    }

    if inner.ends_with('+') {
      return self.parse_one_or_more(inner);
    }

    if !inner.is_empty() {
      return Self::parse_named_rule(inner);
    }

    Err(MetaError::InvalidExpression {
      position: 0,
      expression: input.to_string(),
    })
  }

  fn parse_character(input: &'a str) -> Result<Expression<'a>, MetaError> {
    let input = input.trim();

    if !input.starts_with("'") || !input.ends_with("'") {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let character = &input[1..input.len() - 1];

    if character.len() != 1 {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    Ok(Expression::Char(character))
  }

  fn parse_sequence(self, input: &'a str) -> Result<Expression<'a>, MetaError> {
    let parts = input.split(',').map(|part| part.trim()).collect::<Vec<&str>>();

    if parts.len() < 2 {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let expressions = parts
      .iter()
      .map(|part| self.parse_expression(part))
      .collect::<Result<Vec<Expression>, MetaError>>()?;

    Ok(Expression::Sequence(expressions))
  }

  fn parse_choice(self, input: &'a str) -> Result<Expression<'a>, MetaError> {
    let parts = input.split('|').map(|part| part.trim()).collect::<Vec<&str>>();

    if parts.len() < 2 {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let expressions = parts
      .iter()
      .map(|part| self.parse_expression(part))
      .collect::<Result<Vec<Expression>, MetaError>>()?;

    Ok(Expression::Choice(expressions))
  }

  fn parse_zero_or_more(self, input: &'a str) -> Result<Expression<'a>, MetaError> {
    if !input.ends_with('*') {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let inner = &input[..input.len() - 1].trim();

    let expression = self.parse_expression(inner)?;

    Ok(Expression::ZeroOrMore(Box::new(expression)))
  }

  fn parse_one_or_more(self, input: &'a str) -> Result<Expression<'a>, MetaError> {
    if !input.ends_with('+') {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    let inner = &input[..input.len() - 1].trim();

    let expression = self.parse_expression(inner)?;

    Ok(Expression::OneOrMore(Box::new(expression)))
  }

  fn parse_named_rule(input: &'a str) -> Result<Expression<'a>, MetaError> {
    let input = input.trim();

    if input.is_empty() {
      return Err(MetaError::InvalidExpression {
        position: 0,
        expression: input.to_string(),
      });
    }

    Ok(Expression::NamedRule(input))
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn test_meta_new() {
    let meta = Meta::new();
    assert_eq!(meta, Meta {});
  }

  #[test]
  fn test_meta_generate() {
    let meta = Meta::new();
    let input = "
      char_c := { 'c' }
      sequence := { char_c, char_c }
      choice := { char_c | sequence }
      zero_or_more := { char_c* }
      one_or_more := { char_c+ }
      named_rule := { char_c }
      complex := { 'a' | { 'b', char_c } }
    ";
    let grammar = meta.generate(input).unwrap();

    assert_eq!(grammar.get("char_c").unwrap().name, "char_c");
    assert_eq!(grammar.get("sequence").unwrap().name, "sequence");
    assert_eq!(grammar.get("choice").unwrap().name, "choice");
    assert_eq!(grammar.get("zero_or_more").unwrap().name, "zero_or_more");
    assert_eq!(grammar.get("one_or_more").unwrap().name, "one_or_more");
    assert_eq!(grammar.get("named_rule").unwrap().name, "named_rule");
    assert_eq!(grammar.get("complex").unwrap().name, "complex");
  }

  #[test]
  fn test_meta_generate_multiline() {
    let meta = Meta::new();
    let input = "
      char_c := { 'c' }
      sequence := { char_c, char_c }
      choice := { char_c | sequence }
      zero_or_more := { char_c* }
      one_or_more := { char_c+ }
      named_rule := { char_c }
      complex := { 'a' | {
          'b', char_c
        }
      }
    ";
    let grammar = meta.generate(input).unwrap();

    assert_eq!(grammar.get("char_c").unwrap().name, "char_c");
    assert_eq!(grammar.get("sequence").unwrap().name, "sequence");
    assert_eq!(grammar.get("choice").unwrap().name, "choice");
    assert_eq!(grammar.get("zero_or_more").unwrap().name, "zero_or_more");
    assert_eq!(grammar.get("one_or_more").unwrap().name, "one_or_more");
    assert_eq!(grammar.get("named_rule").unwrap().name, "named_rule");
    assert_eq!(grammar.get("complex").unwrap().name, "complex");
  }

  #[test]
  fn test_meta_generate_comments() {
    let meta = Meta::new();
    let input = "
      // This is a char
      char_c := { 'c' }
      // This is a sequence
      sequence := { char_c, char_c }
      // This is a choice
      choice := { char_c | sequence }
      // This is zero or more
      zero_or_more := { char_c* }
      // This is one or more
      one_or_more := { char_c+ }
      // This is a named rule
      named_rule := { char_c }
      // This is a complex expr
      complex := { 'a' | { 'b', char_c } }
    ";
    let grammar = meta.generate(input).unwrap();

    assert_eq!(grammar.get("char_c").unwrap().name, "char_c");
    assert_eq!(grammar.get("sequence").unwrap().name, "sequence");
    assert_eq!(grammar.get("choice").unwrap().name, "choice");
    assert_eq!(grammar.get("zero_or_more").unwrap().name, "zero_or_more");
    assert_eq!(grammar.get("one_or_more").unwrap().name, "one_or_more");
    assert_eq!(grammar.get("named_rule").unwrap().name, "named_rule");
    assert_eq!(grammar.get("complex").unwrap().name, "complex");
  }
}
